# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 03:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hostinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(default='\u672a\u5206\u7ec4', max_length=30, verbose_name='\u5206\u7ec4')),
                ('name', models.CharField(max_length=30, verbose_name='\u4e3b\u673a\u540d')),
                ('ip', models.GenericIPAddressField(verbose_name='ip \u5730\u5740')),
                ('rootname', models.CharField(max_length=50, verbose_name='\u7ba1\u7406\u5458\u7528\u6237\u540d')),
                ('rootpassword', models.CharField(max_length=30, verbose_name='\u5bc6\u7801')),
                ('sshport', models.IntegerField(verbose_name='SSH\u7aef\u53e3')),
                ('description', models.TextField(default='\u65e0', verbose_name='\u7b80\u8ff0\u4fe1\u606f')),
                ('spare', models.CharField(blank=True, max_length=30, verbose_name='\u5907\u7528\u6269\u5c55\u5b57\u6bb5')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='\u6700\u540e\u4fee\u6539\u65e5\u671f')),
                ('createdate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u521b\u5efa/\u6dfb\u52a0\u65e5\u671f')),
            ],
        ),
    ]
