# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-10 06:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(default='\u672a\u5206\u7ec4', max_length=50, verbose_name='\u7ec4\u540d')),
            ],
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_set', to='host.Group'),
        ),
    ]
