# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 01:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0002_auto_20160910_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group_script',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=50, verbose_name='\u529f\u80fd\u7c7b\u522b')),
            ],
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=60, verbose_name='\u811a\u672c\u6587\u4ef6\u540d')),
                ('filepath', models.CharField(max_length=60, verbose_name='\u811a\u672c\u8def\u5f84')),
                ('description', models.TextField(verbose_name='\u529f\u80fd\u7b80\u8ff0')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='\u6700\u540e\u4fee\u6539\u65e5\u671f')),
                ('createdate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u521b\u5efa/\u6dfb\u52a0\u65e5\u671f')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupscrit_set', to='host.Group_script')),
            ],
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='group',
            field=models.ForeignKey(default='\u672a\u5206\u7ec4', on_delete=django.db.models.deletion.CASCADE, related_name='group_set', to='host.Group'),
        ),
        migrations.AddField(
            model_name='hostinfo',
            name='script',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='host.Script'),
        ),
    ]
