# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0003_auto_20160912_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='filepath',
            field=models.FileField(max_length=60, upload_to=b'', verbose_name='\u811a\u672c\u8def\u5f84'),
        ),
    ]
