# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0004_auto_20160912_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='filepath',
            field=models.FileField(upload_to='upload/', verbose_name='\u811a\u672c\u8def\u5f84'),
        ),
    ]
