# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 06:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0006_logsplit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logsplit',
            name='host',
        ),
        migrations.DeleteModel(
            name='LogSplit',
        ),
    ]
