# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-09 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0009_hostinfo_host_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostinfo',
            name='docker_remote_api_port',
            field=models.IntegerField(blank=True, null=True, verbose_name='docker\u8fdc\u7a0bAPI\u7aef\u53e3'),
        ),
    ]
