# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-14 01:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0010_hostinfo_docker_remote_api_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostinfo',
            name='forward_host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='host.hostinfo', verbose_name='\u8df3\u8f6c\u4e3b\u673a'),
        ),
    ]
