# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-08 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='curr_tag',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='\u5f53\u524d\u7248\u672c\u53f7'),
        ),
    ]
