# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-09 05:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20161109_0837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server',
            old_name='tag',
            new_name='curr_tag',
        ),
    ]
