# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-09 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20161109_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='curr_env_tag',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='\u5f53\u524d\u73af\u5883\u7248\u672c\u53f7'),
        ),
        migrations.AlterField(
            model_name='server',
            name='curr_tag',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='\u5f53\u524d\u4ee3\u7801\u7248\u672c\u53f7'),
        ),
    ]
