# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-09 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_auto_20161109_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='HttpChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True, verbose_name='message')),
                ('take_out', models.BooleanField(default=False, verbose_name='\u662f\u5426\u53d6\u8d70\u6d88\u606f')),
            ],
        ),
    ]
