# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-16 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_auto_20161114_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='httpchannel',
            name='random',
            field=models.IntegerField(default=0, verbose_name='\u6d88\u606ftoken\u968f\u673a\u6570'),
        ),
        migrations.AlterField(
            model_name='environment',
            name='env_group',
            field=models.ManyToManyField(blank=True, related_name='Env_Group', to='host.Group'),
        ),
    ]
