# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-30 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_auto_20161125_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='server_conf',
        ),
        migrations.AddField(
            model_name='server',
            name='server_conf',
            field=models.ManyToManyField(blank=True, null=True, related_name='configurefile', to='server.ConfigureFile'),
        ),
    ]
