# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-08 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_auto_20161130_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='ignore_file',
            field=models.TextField(blank=True, null=True, verbose_name='\u90e8\u7f72\u65f6\u5ffd\u7565\u6587\u4ef6'),
        ),
    ]
