# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-14 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0012_server_ignore_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='server_conf',
            field=models.ManyToManyField(blank=True, related_name='configurefile', to='server.ConfigureFile'),
        ),
    ]
