# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-22 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0014_channelforlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelforlog',
            name='group_num',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u6bcf\u4e2a\u901a\u9053\u7ec4\u7684\u4eba\u6570'),
        ),
        migrations.AlterField(
            model_name='channelforlog',
            name='channel_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='\u6bcf\u4e2a\u901a\u9053\u7ec4_ID'),
        ),
    ]
