# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-23 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0015_auto_20161222_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelforlog',
            name='enforce',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u5df2\u7ecf\u5f3a\u5236\u6253\u5370'),
        ),
    ]
