# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 02:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('host', '0005_auto_20160912_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogSplit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.DateTimeField(verbose_name='\u8981\u622a\u53d6\u7684\u5f00\u59cb\u65f6\u95f4')),
                ('stoptime', models.DateTimeField(verbose_name='\u8981\u622a\u53d6\u7684\u622a\u6b62\u65f6\u95f4')),
                ('logfilename', models.CharField(default='console.log', max_length=60, verbose_name='\u65e5\u5fd7\u6587\u4ef6\u540d(\u9ed8\u8ba4console.log)')),
                ('creatfilename', models.CharField(blank=True, max_length=60, null=True, verbose_name='\u8981\u751f\u6210\u7684\u6587\u4ef6\u540d(\u9ed8\u8ba4\u5f53\u524d\u65f6\u95f4)')),
                ('createtime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u521b\u5efa/\u6dfb\u52a0\u65e5\u671f')),
                ('host', models.ForeignKey(on_delete='id', to='host.hostinfo', to_field='id')),
            ],
        ),
    ]
