# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 02:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LogSplit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logsplit',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='host.hostinfo'),
        ),
    ]
