# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 03:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LogSplit', '0003_auto_20160912_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logsplit',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_set', to='host.hostinfo'),
        ),
    ]
