# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 06:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LogSplit', '0004_auto_20160912_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logsplit',
            name='host',
        ),
        migrations.DeleteModel(
            name='LogSplit',
        ),
    ]
