# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogSplit', '0006_logsplit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logsplit',
            name='starttime',
            field=models.CharField(max_length=30, verbose_name='\u8981\u622a\u53d6\u7684\u5f00\u59cb\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='logsplit',
            name='stoptime',
            field=models.CharField(max_length=30, verbose_name='\u8981\u622a\u53d6\u7684\u622a\u6b62\u65f6\u95f4'),
        ),
    ]
