# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogSplit', '0008_auto_20160912_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicename',
            name='name',
            field=models.CharField(max_length=50, verbose_name='\u670d\u52a1\u540d'),
        ),
    ]
