# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 09:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LogSplit', '0011_auto_20160912_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logsplit',
            name='host',
        ),
        migrations.RemoveField(
            model_name='logsplit',
            name='server',
        ),
        migrations.DeleteModel(
            name='LogSplit',
        ),
    ]
