# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogSplit', '0013_logsplit'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicename',
            name='is_container',
            field=models.BooleanField(default=True, verbose_name='\u670d\u52a1\u662f\u5426\u5728\u5bb9\u5668\u91cc'),
            preserve_default=False,
        ),
    ]
