# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogSplit', '0014_servicename_is_container'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicename',
            name='port',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u670d\u52a1\u7aef\u53e3'),
        ),
    ]
