# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogSplit', '0015_servicename_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicename',
            name='timetype',
            field=models.CharField(default='-', max_length=2, verbose_name='\u65f6\u95f4\u683c\u5f0f\u5206\u5272\u7b26'),
        ),
    ]
