# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-19 01:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0007_auto_20160912_1440'),
        ('LogSplit', '0016_servicename_timetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logsplit',
            name='host',
        ),
        migrations.AddField(
            model_name='servicename',
            name='forwarding_host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forwarding_host_set', to='host.hostinfo'),
        ),
        migrations.AddField(
            model_name='servicename',
            name='is_botnet',
            field=models.BooleanField(default=False),
        ),
    ]
