# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-29 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogSplit', '0018_auto_20160919_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='logsplit',
            name='linenum',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u6700\u540e\u591a\u5c11\u884c'),
        ),
    ]
