# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-19 06:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0013_auto_20161214_0933'),
        ('LogSplit', '0019_logsplit_linenum'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicename',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.Server', verbose_name='\u5173\u8054\u670d\u52a1'),
        ),
        migrations.AlterField(
            model_name='servicename',
            name='forwarding_host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forwarding_host_set', to='host.hostinfo', verbose_name='\u8df3\u677f\u4e3b\u673a'),
        ),
        migrations.AlterField(
            model_name='servicename',
            name='is_container',
            field=models.BooleanField(default=True, verbose_name='\u670d\u52a1\u662f\u5426\u5728\u5bb9\u5668\u91cc'),
        ),
    ]
