# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-19 07:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('LogSplit', '0020_auto_20161219_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicename',
            name='createdate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u521b\u5efa/\u6dfb\u52a0\u65e5\u671f'),
        ),
        migrations.AddField(
            model_name='servicename',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='\u6700\u540e\u4fee\u6539\u65e5\u671f'),
        ),
    ]
